[project]
name = "identity"
version = "0.1.0"
description = "Decentralized fuzzy extractor"
requires-python = ">=3.13"
dependencies = [
    "numpy==2.2.6",
    "fuzzy-extractor==0.3.0",
    "keri==1.3.1",
    "pynput==1.8.1", # for biometric input
]
